[package]
name = "codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
cranelift-frontend = "0.102"
cranelift-codegen = { version = "0.102", features = ["default", "all-arch"] }
cranelift-module = "0.102"
cranelift-object = "0.102"
cranelift-native = "0.102"
parser = { path = "../parser" }
